### PR TITLE
Why questions answered

### PR DESCRIPTION
**Pull request by henkvancann**

### CODE REVIEW

**Comment by henkvancann** [comment]
last commit message should have been:

explanation why import in Tor, and that's not possible to export priv key from tor to sign with

**Comment by gorazdko** [comment]
> explanation why import in Tor, and that's not possible to export priv key from tor to sign with

To be clear: while we are not able to export Tor's secret key to `minisign` format, it is still possible do signing with it. In this case `minisign` would have to be adapted to read/parse the key in Tor format.

(This is just an informal explanation, no need to put it into docs)

**Comment by henkvancann** [comment]
Great, I'll change my text accordingly, if you havent done that already
  

  

  

  
  
  
  
  
>

**Review by ChristopherA — APPROVED** [review]
ACK

**Comment by ChristopherA** [comment]
I may quibble with some wording, but this is a good start. Merging.

**Pull request merged**
